### ISSUE TITLE
Utility functions

### ISSUE THREAD

**Issue by ivanvenosdel** [rags/pynt#10]
Would you like any of these functions? If so, I can submit them as a pull request (with tests).

https://github.com/WimpyAnalytics/pynt-of-django/blob/master/pyntofdjango/utils.py

**Comment by rags** [comment]
First of all. Nice package for django.
The cd, exec are nice functions to have, Thank you. We need to think about how to include them in pynt.
I'm think perhaps as a separate package called pynt-extras. So pynt still remains thin and light-weight. What do you think?

**Comment by ivanvenosdel** [comment]
Yeah I think that is a good idea. In addition to keeping things lean the execute function does have the likelihood of causing a little controversy. 
This is due to having to decide whether to pass shell_execute=True/False when calling Popen. I chose to pass False as I feel that is safer. This has the affect of making execute expect args to be passed individually rather than one space separated string.

So if it were a task: 
```
pynt execute[ls,-l]
```

As apposed to:
```
pynt execute["ls -l"]
```

 Some will find that annoying, like those coming from fabric.

**Comment by ivanvenosdel** [comment]
I have a task in for this on the pynt-of-django project now though I won't be able to tackle creating a whole new project for some time. Maybe about a month. So if you get to it first, let me know, I would be happy to prepare a pull request to contribute these there.

**Comment by rags** [comment]
I will create the project/repo and let you know. So you can send a merge request and we will get these changes in.

**Comment by rags** [comment]
I have created a new repo pynt-contrib. Lets start by adding safe_cd and execute. I'll be happy to add it but I think it'll be better if you raise a pull request so its attributed to you. 

The functions will go into this file for now https://github.com/rags/pynt-contrib/blob/master/pynt/contrib/__init__.py

**Comment by ivanvenosdel** [comment]
Awesome. The pull request is in.

**Comment by rags** [comment]
Thank you. Will pull soon.
