### ISSUE TITLE
Using pynt on build server

### ISSUE THREAD

**Issue by barakschiller** [rags/pynt#11]
Hi,
I really like pynt and would like to use it as a build tool for some of my python projects.
My builds are already using docker to allow me to create a container, install my dependencies and then run the tests. To use pynt as a build system I need to install it **outside** the container on the build server. Do you have any ideas on the easiest way to do that (assuming I can't just pip install things on the build server)?

**Comment by rags** [comment]
One option is to bundle pynt with the source code, so it can run on any machine without requiring additional pip install.

Look at virtualenv
http://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/
