### ISSUE TITLE
add it to a Wikipedia article

### ISSUE THREAD

**Issue by jabbalaci** [rags/pynt#15]
It would be a good idea to add your build tool to this list: https://en.wikipedia.org/wiki/List_of_build_automation_software . SCons is there, another build tool written in Python.

I also want to say thanks for this project! It's perfect for my needs.

**Comment by rags** [comment]
Hi,
Thanks for the shout out. This is great suggestion. I'll look into it

**Comment by jabbalaci** [comment]
As it got done, we can close it.
